name: du_bist_ein_erfahrener_flutter_entwickler_erste
description: Ein produktionsreifes Flutter-Projekt für eine To-Do-App mit State-Management, Dark- & Light-Theme und mehr.
version: 1.0.0+1
publish_to: 'none' # This is a private project. Remove this line if you want to publish to pub.dev.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8  # Für CupertinoIcons (iOS-Style Icons)

  # Add any other dependencies you need for your app here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

# Add any other configurations you need for your app here